#!/bin/bash

psql -d ${POSTGRES_DB} -U ${POSTGRES_USER} <<-END
	CREATE SCHEMA ${DB_SCHEMA};
    CREATE ROLE ${DB_ANON_ROLE} NOLOGIN;
    GRANT USAGE ON SCHEMA ${DB_SCHEMA} TO ${DB_ANON_ROLE};
    ALTER DEFAULT PRIVILEGES IN SCHEMA ${DB_SCHEMA} GRANT SELECT ON TABLES TO ${DB_ANON_ROLE};
    CREATE ROLE ${DB_CONN_ROLE} NOINHERIT LOGIN PASSWORD '${DB_CONN_PWD}';
	GRANT ${DB_ANON_ROLE} TO ${DB_CONN_ROLE};
    CREATE ROLE ressources_user NOLOGIN;
    GRANT ressources_user TO ${DB_CONN_ROLE};
END